<!-- <!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Réservation - SportCoach</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    Navigation
    <nav class="navbar">
        <div class="container">
            <div class="nav-wrapper">
                <a href="index.html" class="logo">
                    <i class="fas fa-dumbbell"></i>
                    <span>SportCoach</span>
                </a>
                <div class="nav-buttons">
                    <a href="client-dashboard.html" class="btn btn-outline">
                        <i class="fas fa-user"></i>
                        Mon compte
                    </a>
                </div>
            </div>
        </div>
    </nav>

    Booking Section
    <section class="booking-section">
        <div class="container">
            <a href="coach-profile.html" class="back-link">
                <i class="fas fa-arrow-left"></i>
                Retour au profil
            </a>

            <div class="booking-grid">
                Booking Form
                <div class="booking-main">
                    <h1><i class="fas fa-calendar-plus"></i> Réserver une séance</h1>
                    
                    <div class="booking-steps">
                        <div class="step active" data-step="1">
                            <span class="step-number">1</span>
                            <span class="step-label">Date & Heure</span>
                        </div>
                        <div class="step" data-step="2">
                            <span class="step-number">2</span>
                            <span class="step-label">Informations</span>
                        </div>
                        <div class="step" data-step="3">
                            <span class="step-number">3</span>
                            <span class="step-label">Confirmation</span>
                        </div>
                    </div>

                    Step 1: Date & Time
                    <div class="step-content active" id="step1">
                        <h2>Choisissez une date et un horaire</h2>
                        
                        <div class="calendar-container">
                            <div class="calendar-header">
                                <button class="calendar-nav" id="prevMonth">
                                    <i class="fas fa-chevron-left"></i>
                                </button>
                                <h3 id="currentMonth">Décembre 2024</h3>
                                <button class="calendar-nav" id="nextMonth">
                                    <i class="fas fa-chevron-right"></i>
                                </button>
                            </div>
                            <div class="calendar-grid" id="calendarGrid">
                                Calendar will be generated by JS
                            </div>
                        </div>

                        <div class="time-slots" id="timeSlots" style="display: none;">
                            <h3>Créneaux disponibles</h3>
                            <div class="slots-grid">
                                <button class="time-slot" data-time="09:00">09:00</button>
                                <button class="time-slot" data-time="10:00">10:00</button>
                                <button class="time-slot" data-time="11:00">11:00</button>
                                <button class="time-slot" data-time="14:00">14:00</button>
                                <button class="time-slot" data-time="15:00">15:00</button>
                                <button class="time-slot" data-time="16:00">16:00</button>
                                <button class="time-slot" data-time="17:00">17:00</button>
                                <button class="time-slot" data-time="18:00">18:00</button>
                            </div>
                        </div>

                        <button class="btn btn-primary" id="nextStep1" disabled>
                            Continuer
                            <i class="fas fa-arrow-right"></i>
                        </button>
                    </div>

                    Step 2: Information
                    <div class="step-content" id="step2">
                        <h2>Informations complémentaires</h2>
                        
                        <form id="bookingForm">
                            <div class="form-group">
                                <label for="sessionType">
                                    <i class="fas fa-users"></i>
                                    Type de séance
                                </label>
                                <select id="sessionType" name="sessionType" required>
                                    <option value="">Sélectionnez un type</option>
                                    <option value="individual">Individuelle</option>
                                    <option value="group">En groupe (2-4 personnes)</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="level">
                                    <i class="fas fa-chart-line"></i>
                                    Votre niveau
                                </label>
                                <select id="level" name="level" required>
                                    <option value="">Sélectionnez votre niveau</option>
                                    <option value="beginner">Débutant</option>
                                    <option value="intermediate">Intermédiaire</option>
                                    <option value="advanced">Avancé</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="objectives">
                                    <i class="fas fa-bullseye"></i>
                                    Objectifs de la séance
                                </label>
                                <textarea 
                                    id="objectives" 
                                    name="objectives" 
                                    rows="4" 
                                    placeholder="Décrivez vos objectifs et attentes..."
                                    required
                                ></textarea>
                            </div>

                            <div class="form-group">
                                <label for="notes">
                                    <i class="fas fa-note-sticky"></i>
                                    Notes supplémentaires (optionnel)
                                </label>
                                <textarea 
                                    id="notes" 
                                    name="notes" 
                                    rows="3" 
                                    placeholder="Informations médicales, disponibilités spécifiques..."
                                ></textarea>
                            </div>
                        </form>

                        <div class="step-buttons">
                            <button class="btn btn-outline" id="prevStep2">
                                <i class="fas fa-arrow-left"></i>
                                Retour
                            </button>
                            <button class="btn btn-primary" id="nextStep2">
                                Continuer
                                <i class="fas fa-arrow-right"></i>
                            </button>
                        </div>
                    </div>

                    Step 3: Confirmation
                    <div class="step-content" id="step3">
                        <h2>Confirmation de réservation</h2>
                        
                        <div class="confirmation-summary">
                            <div class="summary-section">
                                <h3><i class="fas fa-calendar-check"></i> Détails de la séance</h3>
                                <div class="summary-item">
                                    <span class="label">Date :</span>
                                    <span class="value" id="summaryDate">-</span>
                                </div>
                                <div class="summary-item">
                                    <span class="label">Heure :</span>
                                    <span class="value" id="summaryTime">-</span>
                                </div>
                                <div class="summary-item">
                                    <span class="label">Durée :</span>
                                    <span class="value">60 minutes</span>
                                </div>
                                <div class="summary-item">
                                    <span class="label">Type :</span>
                                    <span class="value" id="summaryType">-</span>
                                </div>
                            </div>

                            <div class="summary-section">
                                <h3><i class="fas fa-user"></i> Coach</h3>
                                <div class="coach-summary">
                                    <img src="https://via.placeholder.com/60" alt="Coach">
                                    <div>
                                        <strong>Mohammed Benali</strong>
                                        <p>Football & Préparation Physique</p>
                                    </div>
                                </div>
                            </div>

                            <div class="summary-section">
                                <h3><i class="fas fa-credit-card"></i> Paiement</h3>
                                <div class="price-breakdown">
                                    <div class="price-item">
                                        <span>Séance</span>
                                        <span>200 DH</span>
                                    </div>
                                    <div class="price-item total">
                                        <strong>Total</strong>
                                        <strong>200 DH</strong>
                                    </div>
                                </div>
                            </div>

                            <div class="terms-checkbox">
                                <label class="checkbox-label">
                                    <input type="checkbox" id="acceptTerms" required>
                                    <span>J'accepte les <a href="#">conditions d'annulation</a> et la <a href="#">politique de remboursement</a></span>
                                </label>
                            </div>
                        </div>

                        <div class="step-buttons">
                            <button class="btn btn-outline" id="prevStep3">
                                <i class="fas fa-arrow-left"></i>
                                Retour
                            </button>
                            <button class="btn btn-primary" id="confirmBooking" disabled>
                                <i class="fas fa-check"></i>
                                Confirmer la réservation
                            </button>
                        </div>
                    </div>
                </div>

                Booking Summary Sidebar
                <div class="booking-sidebar">
                    <div class="sidebar-card sticky">
                        <h3><i class="fas fa-file-alt"></i> Résumé</h3>
                        
                        <div class="coach-mini">
                            <img src="https://via.placeholder.com/60" alt="Coach">
                            <div>
                                <strong>Mohammed Benali</strong>
                                <p>Football & Préparation Physique</p>
                            </div>
                        </div>

                        <div class="sidebar-divider"></div>

                        <div class="booking-summary-item">
                            <i class="fas fa-calendar"></i>
                            <div>
                                <span class="label">Date</span>
                                <span class="value" id="sidebarDate">Non sélectionnée</span>
                            </div>
                        </div>

                        <div class="booking-summary-item">
                            <i class="fas fa-clock"></i>
                            <div>
                                <span class="label">Heure</span>
                                <span class="value" id="sidebarTime">Non sélectionnée</span>
                            </div>
                        </div>

                        <div class="booking-summary-item">
                            <i class="fas fa-hourglass-half"></i>
                            <div>
                                <span class="label">Durée</span>
                                <span class="value">60 minutes</span>
                            </div>
                        </div>

                        <div class="sidebar-divider"></div>

                        <div class="price-summary">
                            <div class="price-row">
                                <span>Prix de la séance</span>
                                <span>200 DH</span>
                            </div>
                            <div class="price-row total">
                                <strong>Total</strong>
                                <strong>200 DH</strong>
                            </div>
                        </div>

                        <div class="help-box">
                            <i class="fas fa-question-circle"></i>
                            <p>Besoin d'aide ?</p>
                            <a href="#">Contactez-nous</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    Footer
    <footer class="footer">
        <div class="container">
            <div class="footer-bottom">
                <p>&copy; 2024 SportCoach. Tous droits réservés.</p>
            </div>
        </div>
    </footer>

    <script src="js/main.js"></script>
    <script>
        // Booking flow management
        let currentStep = 1;
        let selectedDate = null;
        let selectedTime = null;

        // Simple calendar generation
        function generateCalendar() {
            const grid = document.getElementById('calendarGrid');
            const days = ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'];
            
            grid.innerHTML = days.map(day => `<div class="calendar-day-header">${day}</div>`).join('');
            
            for (let i = 1; i <= 31; i++) {
                const dayEl = document.createElement('div');
                dayEl.className = 'calendar-day';
                if (i < 16) dayEl.classList.add('disabled');
                dayEl.textContent = i;
                dayEl.addEventListener('click', () => selectDate(i));
                grid.appendChild(dayEl);
            }
        }

        function selectDate(day) {
            if (day < 16) return;
            
            document.querySelectorAll('.calendar-day').forEach(d => d.classList.remove('selected'));
            event.target.classList.add('selected');
            selectedDate = `${day} Décembre 2024`;
            document.getElementById('timeSlots').style.display = 'block';
            updateSidebar();
        }

        document.querySelectorAll('.time-slot').forEach(slot => {
            slot.addEventListener('click', function() {
                document.querySelectorAll('.time-slot').forEach(s => s.classList.remove('selected'));
                this.classList.add('selected');
                selectedTime = this.dataset.time;
                document.getElementById('nextStep1').disabled = false;
                updateSidebar();
            });
        });

        function updateSidebar() {
            document.getElementById('sidebarDate').textContent = selectedDate || 'Non sélectionnée';
            document.getElementById('sidebarTime').textContent = selectedTime || 'Non sélectionnée';
        }

        function goToStep(step) {
            document.querySelectorAll('.step-content').forEach(s => s.classList.remove('active'));
            document.querySelectorAll('.step').forEach(s => s.classList.remove('active'));
            
            document.getElementById(`step${step}`).classList.add('active');
            document.querySelector(`.step[data-step="${step}"]`).classList.add('active');
            currentStep = step;
            
            window.scrollTo({ top: 0, behavior: 'smooth' });
        }

        document.getElementById('nextStep1').addEventListener('click', () => goToStep(2));
        document.getElementById('prevStep2').addEventListener('click', () => goToStep(1));
        document.getElementById('nextStep2').addEventListener('click', () => {
            const form = document.getElementById('bookingForm');
            if (form.checkValidity()) {
                document.getElementById('summaryDate').textContent = selectedDate;
                document.getElementById('summaryTime').textContent = selectedTime;
                document.getElementById('summaryType').textContent = 
                    document.getElementById('sessionType').selectedOptions[0].text;
                goToStep(3);
            } else {
                form.reportValidity();
            }
        });
        document.getElementById('prevStep3').addEventListener('click', () => goToStep(2));

        document.getElementById('acceptTerms').addEventListener('change', function() {
            document.getElementById('confirmBooking').disabled = !this.checked;
        });

        document.getElementById('confirmBooking').addEventListener('click', () => {
            alert('Réservation confirmée ! Vous recevrez un email de confirmation.');
            window.location.href = 'client-dashboard.html';
        });

        generateCalendar();
    </script>
</body>
</html> -->




<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <title>Réserver une séance | SportCoach</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

  <script>
    tailwind.config = {
      theme: {
        extend: {
          colors: {
            primary: '#0f172a',
            accent: '#22c55e',
            soft: '#f8fafc'
          }
        }
      }
    }
  </script>
</head>

<body class="bg-soft text-gray-800">

<!-- NAV -->
<?php
require('./components/header.php')
?>

<!-- CONTENT -->
<section class="max-w-4xl mx-auto px-6 py-16">

  <a href="#" class="text-sm text-gray-500 hover:text-accent flex items-center gap-2 mb-6">
    <i class="fas fa-arrow-left"></i> Retour au profil
  </a>

  <div class="bg-white rounded-xl shadow p-8 grid md:grid-cols-3 gap-8">

    <!-- FORM -->
    <div class="md:col-span-2">
      <h1 class="text-3xl font-bold mb-6">
        <i class="fas fa-calendar-plus text-accent"></i> Réserver une séance
      </h1>

      <!-- ALERT -->
      <div id="availabilityAlert" class="hidden mb-6 p-4 rounded-lg text-sm"></div>

      <form class="space-y-6">

        <div>
          <label class="block mb-1 font-medium">Date</label>
          <input type="date" id="date"
            class="w-full border rounded-lg px-4 py-2 focus:ring-2 focus:ring-accent">
        </div>

        <div>
          <label class="block mb-1 font-medium">Heure</label>
          <input type="time" id="time"
            class="w-full border rounded-lg px-4 py-2 focus:ring-2 focus:ring-accent">
        </div>

        <div>
          <label class="block mb-1 font-medium">Type de séance</label>
          <select class="w-full border rounded-lg px-4 py-2">
            <option>Individuelle</option>
            <option>Groupe</option>
          </select>
        </div>

        <div>
          <label class="block mb-1 font-medium">Objectifs</label>
          <textarea rows="3"
            class="w-full border rounded-lg px-4 py-2"
            placeholder="Perte de poids, technique, endurance..."></textarea>
        </div>

        <div class="flex gap-4">
          <button type="button"
            onclick="checkAvailability()"
            class="px-6 py-3 border rounded-lg hover:bg-gray-100">
            Vérifier disponibilité
          </button>

          <button type="submit"
            id="confirmBtn"
            disabled
            class="px-6 py-3 bg-accent text-white rounded-lg font-semibold opacity-50 cursor-not-allowed">
            Confirmer réservation
          </button>
        </div>

      </form>
    </div>

    <!-- SIDEBAR -->
    <div class="bg-gray-50 rounded-xl p-6">
      <h3 class="font-bold mb-4">Coach</h3>
      <div class="flex items-center gap-3 mb-6">
        <img src="https://via.placeholder.com/60" class="rounded-full">
        <div>
          <strong>Mohammed Benali</strong>
          <p class="text-sm text-gray-500">Football</p>
        </div>
      </div>

      <div class="border-t pt-4 space-y-2 text-sm">
        <div class="flex justify-between">
          <span>Durée</span>
          <span>60 min</span>
        </div>
        <div class="flex justify-between font-bold">
          <span>Prix</span>
          <span>200 DH</span>
        </div>
      </div>
    </div>

  </div>
</section>

<?php
require('./components/footer.php')
?>

<script>
  function checkAvailability() {
    const date = document.getElementById('date').value;
    const time = document.getElementById('time').value;
    const alertBox = document.getElementById('availabilityAlert');
    const confirmBtn = document.getElementById('confirmBtn');

    if (!date || !time) {
      alertBox.className = "mb-6 p-4 rounded-lg bg-red-100 text-red-700";
      alertBox.textContent = "Veuillez choisir une date et une heure.";
      alertBox.classList.remove('hidden');
      return;
    }

    // MOCK disponibilité
    const available = time !== "14:00";

    if (available) {
      alertBox.className = "mb-6 p-4 rounded-lg bg-green-100 text-green-700";
      alertBox.textContent = "Coach disponible pour ce créneau.";
      confirmBtn.disabled = false;
      confirmBtn.classList.remove('opacity-50','cursor-not-allowed');
    } else {
      alertBox.className = "mb-6 p-4 rounded-lg bg-red-100 text-red-700";
      alertBox.textContent = "Coach non disponible à cette heure.";
      confirmBtn.disabled = true;
      confirmBtn.classList.add('opacity-50','cursor-not-allowed');
    }

    alertBox.classList.remove('hidden');
  }
</script>

</body>
</html>
